#!/usr/bin/env node
/**
 * One-shot merge of AMK-MAP-3 keys into dashboard/data/amk_control_dashboard_map.json
 * Run from hub root: node scripts/_amk_map3_data_merge.mjs && del scripts\\_amk_map3_data_merge.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const p = path.join(ROOT, 'dashboard', 'data', 'amk_control_dashboard_map.json');
const j = JSON.parse(fs.readFileSync(p, 'utf8'));

j.schema = 'amk_control_dashboard_map_v3';
j.phase = 'AMK-MAP-3';
j.page_subtitle =
  'AMK-MAP-3 — universal domain lenses, side catalog, readiness observatory, launch ceremony (read-only metadata). No feedback collection, analytics, deploy, or bridges.';

j.map3_disclaimer =
  'This dashboard does not execute tasks, collect user feedback, deploy, bill, or bridge services. It is a visual command map. Dashboard view ≠ service access. Service listing ≠ entitlement. Rating ≠ certification. Launch readiness ≠ deployment.';

j.domain_views = [
  {
    id: 'amk_operator',
    label: 'AMK-Goku / Operator',
    allowed_sensitivity: ['none', 'learning', 'ops', 'commercial', 'admin', 'security'],
    hidden_section_ids: [],
    welcome_paragraph: '',
    emphasis_hint: 'Full map: receipts, gates, blocked lanes — still no execution from this page.',
  },
  {
    id: 'kids',
    label: 'Kids',
    allowed_sensitivity: ['none', 'learning'],
    hidden_section_ids: [
      'strip',
      'law',
      'ecosystem',
      'health',
      'rhythm',
      'hero',
      'topcards',
      'queue',
      'sealed',
      'projects',
      'safenow',
      'blocked',
      'receipts',
      'inspector',
      'observatory',
      'launch',
    ],
    welcome_paragraph:
      'Welcome — you are seeing a gentle, learning-safe slice of Z-Sanctuary. Grown-up tools, prices, and admin maps are hidden here.',
    emphasis_hint: 'Play, comfort, and friendly learning notes only.',
  },
  {
    id: 'teens',
    label: 'Teens',
    allowed_sensitivity: ['none', 'learning', 'ops'],
    hidden_section_ids: ['blocked', 'receipts', 'observatory', 'launch', 'queue'],
    welcome_paragraph:
      'Guided creativity and study-friendly surfaces. Deployment, billing, and sensitive admin language stay hidden.',
    emphasis_hint: 'Creativity + learning + safety-first language.',
  },
  {
    id: 'adults',
    label: 'Adults',
    allowed_sensitivity: ['none', 'learning', 'ops', 'commercial'],
    hidden_section_ids: [],
    welcome_paragraph: 'Personal tools, services, and family-friendly productivity — admin-only rows stay filtered.',
    emphasis_hint: 'Wellness and services without kid-only framing.',
  },
  {
    id: 'family',
    label: 'Family',
    allowed_sensitivity: ['none', 'learning', 'ops', 'commercial'],
    hidden_section_ids: ['queue'],
    welcome_paragraph: 'Shared household lens: learning, services, and care — not operator admin consoles.',
    emphasis_hint: 'Balances safety with everyday usefulness.',
  },
  {
    id: 'business',
    label: 'Business',
    allowed_sensitivity: ['none', 'learning', 'ops', 'commercial'],
    hidden_section_ids: [],
    welcome_paragraph: 'Service catalog, workflows, and commercial-readiness metadata — no live checkout.',
    emphasis_hint: 'Productivity and compliance-friendly links only.',
  },
  {
    id: 'enterprise',
    label: 'Enterprise',
    allowed_sensitivity: ['none', 'learning', 'ops', 'commercial', 'admin', 'security'],
    hidden_section_ids: [],
    welcome_paragraph: 'Governance, audit, entitlements, and cross-project posture — still read-only here.',
    emphasis_hint: 'VH100 / ZSX / receipts visible when sensitivity allows.',
  },
  {
    id: 'public_visitor',
    label: 'Public Visitor',
    allowed_sensitivity: ['none', 'learning'],
    hidden_section_ids: [
      'strip',
      'law',
      'ecosystem',
      'health',
      'rhythm',
      'hero',
      'topcards',
      'queue',
      'sealed',
      'projects',
      'safenow',
      'blocked',
      'receipts',
      'inspector',
      'observatory',
      'launch',
    ],
    welcome_paragraph: 'High-level, safe descriptions of the Sanctuary — no admin, pricing, or bridge controls.',
    emphasis_hint: 'Orientation only.',
  },
];

j.service_catalog_sidebar = [
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'z_zebras_family_preview',
    display_name: 'Z-Zebras Family (preview)',
    icon: '🦓',
    domain: 'Learning / Accessibility',
    age_suitability: ['kids', 'teens', 'adults', 'family'],
    short_description: 'Local readiness preview for inclusive learning patterns — not a live product.',
    status: 'preview',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A (preview)',
    entitlement_owner: 'Hub metadata only',
    risk_class: 'low',
    signal_color: 'GREEN',
    sensitivity_tier: 'learning',
    related_docs: ['docs/Z_SANCTUARY_MONSTER_PROJECT_MASTER_MAP.md'],
    related_reports: [],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'z_questra',
    display_name: 'Z-QUESTRA',
    icon: '🌿',
    domain: 'Comfort / creativity UI',
    age_suitability: ['teens', 'adults', 'family'],
    short_description: 'Separate Vite comfort lab — build under z-questra/; no live hub bridge in Phase 2.1.',
    status: 'lab',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A',
    entitlement_owner: 'N/A',
    risk_class: 'low',
    signal_color: 'BLUE',
    sensitivity_tier: 'ops',
    related_docs: ['docs/z_zuno_technology_snapshot.md'],
    related_reports: [],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'nav_workstation',
    display_name: 'NAV Workstation',
    icon: '🧭',
    domain: 'Operator catalog',
    age_suitability: ['adults', 'business', 'enterprise', 'amk_operator'],
    short_description: 'Read-only service catalog rail — metadata and doc links.',
    status: 'read_only',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A',
    entitlement_owner: 'See data/z_service_entitlement_catalog.json (metadata)',
    risk_class: 'low',
    signal_color: 'GREEN',
    sensitivity_tier: 'ops',
    related_docs: ['docs/dashboard/Z_UNIVERSE_WORKSTATION_NAVIGATOR.md'],
    related_reports: [],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'z_traffic',
    display_name: 'Z-Traffic Minibots',
    icon: '🚦',
    domain: 'Scripts / posture',
    age_suitability: ['enterprise', 'amk_operator'],
    short_description: 'Minibot signal reports — operator and enterprise lenses.',
    status: 'sealed_reports',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A',
    entitlement_owner: 'N/A',
    risk_class: 'low',
    signal_color: 'GREEN',
    sensitivity_tier: 'admin',
    related_docs: ['docs/Z_TRAFFIC_MINIBOTS.md'],
    related_reports: ['data/reports/z_traffic_minibots_status.json'],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'z_susbv',
    display_name: 'Z-SUSBV benchmarks',
    icon: '📐',
    domain: 'Commercial evidence (metadata)',
    age_suitability: ['business', 'enterprise', 'amk_operator'],
    short_description: 'Evidence-first benchmark metadata — no live research or billing in Phase 1.',
    status: 'metadata_only',
    bridge_status: 'Not connected',
    pricing_owner: 'Policy + docs',
    entitlement_owner: 'Catalog JSON',
    risk_class: 'medium',
    signal_color: 'YELLOW',
    sensitivity_tier: 'commercial',
    related_docs: ['commercial/Z_SUSBV_SANCTUARY_SELF_BENCHMARKS_VALIDATION.md'],
    related_reports: [],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'vh100_core',
    display_name: 'VH100 Security Core',
    icon: '🛡️',
    domain: 'Security doctrine',
    age_suitability: ['enterprise', 'amk_operator'],
    short_description: 'Defensive posture JSON + docs — no attack tooling.',
    status: 'phase_docs',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A',
    entitlement_owner: 'N/A',
    risk_class: 'sacred',
    signal_color: 'BLUE',
    sensitivity_tier: 'security',
    related_docs: ['docs/security/Z_VH100_VEGETA_HARISHA_SECURITY_CORE.md'],
    related_reports: [],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'amk_notifications',
    display_name: 'AMK-Goku Notifications',
    icon: '🔔',
    domain: 'Human confirmation',
    age_suitability: ['adults', 'enterprise', 'amk_operator'],
    short_description: 'Lane queue + local decision stub — no task execution.',
    status: 'AMK-NOTIFY-1',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A',
    entitlement_owner: 'N/A',
    risk_class: 'low',
    signal_color: 'GREEN',
    sensitivity_tier: 'admin',
    related_docs: ['docs/AMK_GOKU_NOTIFICATIONS_PANEL.md'],
    related_reports: ['data/amk_operator_notifications.json'],
  },
  {
    project_id: 'satellite',
    module_id: 'eirmind_ref',
    display_name: 'ÉirMind (reference)',
    icon: '☘️',
    domain: 'Sibling reference',
    age_suitability: ['adults', 'business', 'family', 'amk_operator'],
    short_description: 'Reference-only — no auto-bridge from this hub map.',
    status: 'reference',
    bridge_status: 'Future-gated',
    pricing_owner: 'N/A',
    entitlement_owner: 'N/A',
    risk_class: 'low',
    signal_color: 'BLUE',
    sensitivity_tier: 'ops',
    related_docs: ['docs/Z-HIERARCHY-CHIEF-AND-OBSERVER-VIEW.md'],
    related_reports: [],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'living_pulse',
    display_name: 'Living Pulse (comfort)',
    icon: '🦋',
    domain: 'Ambient / calm UI',
    age_suitability: ['kids', 'teens', 'adults', 'family', 'public_visitor'],
    short_description: 'Optional calm visuals on hub dashboard — operator-toggled.',
    status: 'optional',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A',
    entitlement_owner: 'N/A',
    risk_class: 'low',
    signal_color: 'GREEN',
    sensitivity_tier: 'none',
    related_docs: ['docs/Z-ACOUSTIC-LIVING-PULSE-ARCHITECTURE.md'],
    related_reports: [],
  },
  {
    project_id: 'ZSanctuary_Universe',
    module_id: 'ai_builder_pack',
    display_name: 'AI Builder Pack',
    icon: '📚',
    domain: 'Cursor / docs spine',
    age_suitability: ['teens', 'adults', 'business', 'enterprise', 'amk_operator'],
    short_description: 'Read-only doc pack for builders — not public tutoring.',
    status: 'read_only',
    bridge_status: 'Not connected',
    pricing_owner: 'N/A',
    entitlement_owner: 'N/A',
    risk_class: 'low',
    signal_color: 'GREEN',
    sensitivity_tier: 'ops',
    related_docs: ['docs/AI_BUILDER_CONTEXT.md'],
    related_reports: [],
  },
];

j.readiness_observatory = [
  {
    module_id: 'z_questra_local_notebook',
    display_name: 'Z-QUESTRA (local)',
    readiness_score: 82,
    trust_score: 90,
    accessibility_score: null,
    benchmark_status: 'not_commercial',
    maintenance_signal: 'YELLOW',
    upgrade_need: 'medium',
    feedback_status: 'future_gated',
    inspector_notes: 'Internal readiness metadata only — not a public score.',
  },
  {
    module_id: 'nav_workstation',
    display_name: 'NAV Workstation',
    readiness_score: null,
    trust_score: null,
    accessibility_score: null,
    benchmark_status: 'read_only_phase',
    maintenance_signal: 'GREEN',
    upgrade_need: 'low',
    feedback_status: 'future_gated',
    inspector_notes: 'UNKNOWN numeric scores until a dedicated receipt exists.',
  },
  {
    module_id: 'z_traffic',
    display_name: 'Z-Traffic',
    readiness_score: null,
    trust_score: null,
    accessibility_score: null,
    benchmark_status: 'report_driven',
    maintenance_signal: 'GREEN',
    upgrade_need: 'low',
    feedback_status: 'future_gated',
    inspector_notes: 'Use z_traffic_minibots_status.json as ground signal.',
  },
  {
    module_id: 'z_susbv',
    display_name: 'Z-SUSBV',
    readiness_score: null,
    trust_score: null,
    accessibility_score: null,
    benchmark_status: 'metadata_validation',
    maintenance_signal: 'YELLOW',
    upgrade_need: 'high',
    feedback_status: 'future_gated',
    inspector_notes: 'No live user ratings; consent + privacy + 14 DRP before feedback.',
  },
];

j.inspector_advisory = {
  title: 'AI inspector / upgrade advisor (read-only)',
  intro:
    'These inspectors advise only. They do not execute, auto-upgrade, change pricing, deploy, or merge. Tie-breaks stay with AMK and hub gates.',
  law_line: 'Advise ≠ execute · Recommendation ≠ permission',
  rows: [
    { id: 'z_traffic', label: 'Z-Traffic', watches: 'Proceed / hold lane', source: 'reports + docs' },
    { id: 'car2', label: 'Z-CAR²', watches: 'Duplicate / drift windows', source: 'similarity report' },
    { id: 'susbv', label: 'Z-SUSBV', watches: 'Benchmark / pricing evidence posture', source: 'commercial metadata' },
    { id: 'vh100', label: 'VH100', watches: 'Security posture JSON', source: 'docs + data' },
    { id: 'mcburb_fbap', label: 'MCBURB / FBAP', watches: 'Backup + fire-backs awareness', source: 'policy JSON' },
    { id: 'zuno', label: 'Z-Zuno', watches: 'Coverage truth vs registry', source: 'coverage audit' },
    { id: 'zag', label: 'ZAG', watches: 'Autonomy level bands', source: 'z_autonomy_task_policy.json' },
    { id: 'zebras', label: 'Z-Zebras (preview)', watches: 'Accessibility / inclusive learning readiness', source: 'catalog item' },
  ],
};

const hasMap3Receipt = Array.isArray(j.receipts_reports) && j.receipts_reports.some((r) => r.doc && r.doc.includes('MAP_3'));
if (!hasMap3Receipt) {
  j.receipts_reports.splice(3, 0, {
    label: 'AMK-MAP-3 receipt',
    doc: 'docs/PHASE_AMK_MAP_3_GREEN_RECEIPT.md',
  });
}

j.launch_readiness = {
  ceremony_title: 'Launch Readiness Ceremony',
  status: 'PREPARE',
  status_note:
    'Launch readiness: PREPARE — human release review still required. This is not Cloudflare deploy, not npm publish, not bridge go-live.',
  launch_key_copy:
    'The Launch Key is symbolic: it gathers gates, receipts, and blocked items in one glance. AMK-Goku, Zuno, and Z-Family compassion stories stay outside execution paths until a separate human-approved deploy lane opens.',
  required_gates: [
    'manual_release / release control JSON posture',
    'npm run verify:md (when docs move)',
    'npm run z:traffic + npm run z:car2 for drift posture',
    'npm run dashboard:registry-verify after dashboard edits',
    'AAFRTC / overseer pipeline when scope demands',
  ],
  blocked_categories_mirror: true,
  human_approval_required: true,
};

fs.writeFileSync(p, `${JSON.stringify(j, null, 2)}\n`, 'utf8');
console.log('Merged AMK-MAP-3 keys into', p);
