#!/usr/bin/env node
/**
 * GW-6: classified inventories from hub-scoped discovery.
 * Does not copy assets into the public shell. Does not fill Twin records[].
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const ALLOWED = [
  "READY_FOR_STEWARD_REVIEW",
  "NEEDS_SANITIZATION",
  "NEEDS_IDENTITY_REVIEW",
  "NEEDS_MORE_EVIDENCE",
  "KEEP_PRIVATE",
  "DO_NOT_PUBLISH",
];

function listFiles(dir, exts) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...listFiles(p, exts));
    else if (exts.some((x) => e.name.toLowerCase().endsWith(x))) {
      out.push(path.relative(ROOT, p).replace(/\\/g, "/"));
    }
  }
  return out.sort();
}

function rec(partial) {
  if (!ALLOWED.includes(partial.publication_recommendation)) {
    throw new Error(`bad rec ${partial.id} ${partial.publication_recommendation}`);
  }
  return partial;
}

const gwShots = listFiles(path.join(ROOT, "docs/golden-website"), [".png"]);
const shotMeta = {
  "docs/golden-website/gw-3a/screenshots/01-home-desktop.png": {
    title: "Golden Website Home (GW-3A desktop)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Two-record shell capture. Do not present as the current six-record portfolio.",
  },
  "docs/golden-website/gw-3a/screenshots/02-home-evidence-board.png": {
    title: "Evidence Mode board (GW-3A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Shows Evidence Mode on the two-record shell.",
  },
  "docs/golden-website/gw-3a/screenshots/03-home-evidence-desktop.png": {
    title: "Home with Evidence Mode on (GW-3A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Decorative glow reduced. QUALIFIED remains QUALIFIED.",
  },
  "docs/golden-website/gw-3a/screenshots/04-core-desktop.png": {
    title: "Z-Sanctuary Core page (GW-3A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Core QUALIFIED, not VERIFIED.",
  },
  "docs/golden-website/gw-3a/screenshots/05-navigator-desktop.png": {
    title: "Navigator page (GW-3A desktop)",
    canonical_record: "univ_workstation_navigator",
    time_posture: "historical",
    evidence_state: "SEALED",
    notes: "Sanitized Navigator preview. SEALED is not deployed.",
  },
  "docs/golden-website/gw-3a/screenshots/06-home-skip-focus.png": {
    title: "Skip link focused (GW-3A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Accessibility capture, not a product shot.",
  },
  "docs/golden-website/gw-3a/screenshots/07-home-tablet.png": {
    title: "Home tablet 768 (GW-3A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Viewport evidence. Two-record shell.",
  },
  "docs/golden-website/gw-3a/screenshots/08-home-mobile.png": {
    title: "Home mobile 390 (GW-3A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Viewport evidence. Two-record shell.",
  },
  "docs/golden-website/gw-3a/screenshots/09-navigator-mobile.png": {
    title: "Navigator mobile 390 (GW-3A)",
    canonical_record: "univ_workstation_navigator",
    time_posture: "historical",
    evidence_state: "SEALED",
    notes: "Viewport evidence for Navigator.",
  },
  "docs/golden-website/gw-3a/screenshots/10-home-locked-doors.png": {
    title: "Locked future surfaces (GW-3A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "historical",
    evidence_state: "QUALIFIED",
    notes: "Shows Gallery/Museum/Guide AI locked. Not a claim that they exist as products.",
  },
  "docs/golden-website/gw-4a/screenshots/01-home-portfolio.png": {
    title: "Home six-record portfolio (GW-4A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Current local portfolio preview of six approved records.",
  },
  "docs/golden-website/gw-4a/screenshots/02-portfolio-desktop.png": {
    title: "Portfolio Preview desktop (GW-4A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Six cards plus five Core relationships. Not the Universe map.",
  },
  "docs/golden-website/gw-4a/screenshots/03-drp-desktop.png": {
    title: "14 DRP Protocols page (GW-4A)",
    canonical_record: "fourteen_drp_protocols",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Governance page. Not proof of perfect AI compliance.",
  },
  "docs/golden-website/gw-4a/screenshots/04-eaii-desktop.png": {
    title: "Z-EAII page (GW-4A)",
    canonical_record: "z_eaii",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Oversight inside hierarchy. Not super-intelligence.",
  },
  "docs/golden-website/gw-4a/screenshots/05-qadp-desktop.png": {
    title: "Grounded Questions QADP page (GW-4A)",
    canonical_record: "grounded_questions_qadp",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "QADP is not Golden Guide AI.",
  },
  "docs/golden-website/gw-4a/screenshots/06-observe-desktop.png": {
    title: "Cycle Observe page (GW-4A)",
    canonical_record: "cycle_observe",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Observation/review. Not autonomous intervention.",
  },
  "docs/golden-website/gw-4a/screenshots/07-portfolio-mobile.png": {
    title: "Portfolio Preview mobile (GW-4A)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "390px capture of the six-record portfolio.",
  },
  "docs/golden-website/gw-5/screenshots/01-map-desktop-core.png": {
    title: "Universe Map Core selected (GW-5)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Six-node foundation map. Not the complete Universe.",
  },
  "docs/golden-website/gw-5/screenshots/02-map-desktop-evidence.png": {
    title: "Universe Map Evidence Mode (GW-5)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Evidence Mode does not hide QUALIFIED nodes.",
  },
  "docs/golden-website/gw-5/screenshots/03-map-desktop.png": {
    title: "Universe Map desktop 1440 (GW-5)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Foundation layout at desktop width.",
  },
  "docs/golden-website/gw-5/screenshots/03-map-tablet.png": {
    title: "Universe Map tablet 768 (GW-5)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Foundation layout at tablet width.",
  },
  "docs/golden-website/gw-5/screenshots/03-map-mobile.png": {
    title: "Universe Map mobile 390 (GW-5)",
    canonical_record: "z_sanctuary_core",
    time_posture: "current",
    evidence_state: "QUALIFIED",
    notes: "Stacked six-node layout.",
  },
  "docs/golden-website/gw-5/screenshots/04-map-mobile-panel.png": {
    title: "Universe Map mobile detail panel (GW-5)",
    canonical_record: "univ_workstation_navigator",
    time_posture: "current",
    evidence_state: "SEALED",
    notes: "Navigator node details. No private paths in panel.",
  },
};

const firstVisual = new Set([
  "docs/golden-website/gw-4a/screenshots/01-home-portfolio.png",
  "docs/golden-website/gw-4a/screenshots/02-portfolio-desktop.png",
  "docs/golden-website/gw-4a/screenshots/03-drp-desktop.png",
  "docs/golden-website/gw-4a/screenshots/06-observe-desktop.png",
  "docs/golden-website/gw-5/screenshots/01-map-desktop-core.png",
  "docs/golden-website/gw-3a/screenshots/02-home-evidence-board.png",
]);

const visualAssets = gwShots.map((rel, i) => {
  const m = shotMeta[rel];
  if (!m) throw new Error(`unclassified screenshot ${rel}`);
  return rec({
    id: `VIS-GW-${String(i + 1).padStart(3, "0")}`,
    title: m.title,
    asset_type: "UI_SCREENSHOT",
    source_project: "golden-website-shell",
    canonical_record: m.canonical_record,
    time_posture: m.time_posture,
    evidence_state: m.evidence_state,
    depiction: "REAL UI CAPTURE",
    public_safety_status: "LOCAL_PUBLIC_SAFE_CAPTURE",
    sanitization_required: false,
    publication_recommendation: "READY_FOR_STEWARD_REVIEW",
    first_exhibit: firstVisual.has(rel),
    repo_ref: rel,
    notes: m.notes,
  });
});

visualAssets.push(
  rec({
    id: "VIS-ICIS-FIXTURES",
    title: "ICIS schematic fixtures (grouped)",
    asset_type: "DIAGRAM",
    source_project: "icis",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    time_posture: "current",
    evidence_state: "HOLD",
    depiction: "CONCEPT MOCKUP",
    public_safety_status: "SCIENTIFIC_FIXTURE_NOT_MARKETING",
    sanitization_required: true,
    publication_recommendation: "DO_NOT_PUBLISH",
    first_exhibit: false,
    member_count: 3,
    notes: "Hub-authored schematic SVGs. Not camera photographs. Not Golden Website gallery art. Fixture filenames are retained internally; do not copy into the public shell.",
  }),
  rec({
    id: "VIS-ICIS-NATURAL-IMAGES",
    title: "ICIS natural-image custody (grouped, not listed)",
    asset_type: "OTHER",
    source_project: "icis",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    time_posture: "current",
    evidence_state: "HOLD",
    depiction: "REAL UI CAPTURE",
    public_safety_status: "SCIENTIFIC_CUSTODY",
    sanitization_required: true,
    publication_recommendation: "DO_NOT_PUBLISH",
    first_exhibit: false,
    notes: "Natural-image and model-custody trees are not enumerated here. ICIS remains DO_NOT_PUBLISH for Golden Website.",
  }),
  rec({
    id: "VIS-AUTO-SCREENSHOT-DOCTRINE",
    title: "Auto-screenshots / sounds / detectors doctrine",
    asset_type: "OTHER",
    source_project: "hub-docs",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    time_posture: "future",
    evidence_state: "CONCEPT",
    depiction: "FUTURE VISION",
    public_safety_status: "DOCTRINE_ONLY",
    sanitization_required: true,
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "Consent-first game-capture doctrine. Not a screenshot library and not a Visual Gallery.",
  }),
  rec({
    id: "VIS-RECOVERY-LANE",
    title: "Visual Recovery Lane (chat/project mockups outside this clone)",
    asset_type: "WIDESCREEN_MOCKUP",
    source_project: "not-in-this-clone",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    time_posture: "historical",
    evidence_state: "CONCEPT",
    depiction: "CONCEPT MOCKUP",
    public_safety_status: "UNKNOWN_NOT_IN_HUB",
    sanitization_required: true,
    publication_recommendation: "NEEDS_IDENTITY_REVIEW",
    first_exhibit: false,
    notes: "GW-1 noted chat/project mockups not present in this hub clone. Do not invent them.",
  }),
);

const prototypes = [
  rec({
    id: "PROTO-GW-SHELL",
    title: "Golden Website local foundation shell",
    prototype_class: "WORKING",
    canonical_record: "z_sanctuary_core",
    related_records: [
      "univ_workstation_navigator",
      "fourteen_drp_protocols",
      "cycle_observe",
      "z_eaii",
      "grounded_questions_qadp",
    ],
    public_safe_identity: "The Golden Website — Gateway to the Z-Sanctuary Universe",
    repo_ref: "docs/golden-website/shell/index.html",
    local_data_dependencies: "Sanitized adapter JS only (gw-approved-public-safe.js, gw-map-foundation.js)",
    live_private_api: false,
    sensitive_paths: false,
    fake_live_telemetry_risk: "low",
    external_network: false,
    sanitization_needs: ["Keep Twin empty", "Do not iframe operator HTML"],
    public_demo_suitability: "LOCAL_ONLY_AFTER_STEWARD",
    evidence_refs: ["PHASE_GW_4A_GREEN_RECEIPT", "PHASE_GW_5_GREEN_RECEIPT"],
    publication_recommendation: "READY_FOR_STEWARD_REVIEW",
    first_exhibit: true,
    notes: "Already the public-safe local UI. WORKING frontend is not a public service.",
  }),
  rec({
    id: "PROTO-CYCLE-DASHBOARD",
    title: "Cycle Dashboard (read-only)",
    prototype_class: "WORKING",
    canonical_record: "cycle_observe",
    related_records: [],
    public_safe_identity: "Cycle Observe",
    repo_ref: "dashboard/panels/z-cycle-dashboard-readonly.html",
    local_data_dependencies: "GET same-origin operator report JSON",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "high",
    external_network: false,
    sanitization_needs: ["Strip queue/report internals", "No IPs", "No iframe into shell", "No BLUE=failure story"],
    public_demo_suitability: "NOT_UNTIL_SANITIZED",
    evidence_refs: ["docs/Z_CYCLE_DASHBOARD_SYSTEM.md", "GW4_CAPSULE_CYCLE_OBSERVE"],
    publication_recommendation: "NEEDS_SANITIZATION",
    first_exhibit: true,
    notes: "Local working observation UI. Simulated-as-live risk if reports are shown unfiltered.",
  }),
  rec({
    id: "PROTO-KNOWLEDGE-ASK",
    title: "Z-EAII Knowledge Ask",
    prototype_class: "WORKING",
    canonical_record: "grounded_questions_qadp",
    related_records: ["z_eaii"],
    public_safe_identity: "Grounded Questions (QADP) family — not Golden Guide AI",
    repo_ref: "dashboard/panels/z-eaii-knowledge-ask.html",
    local_data_dependencies: "Operator knowledge index fetch",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["No private registries at browser runtime", "Do not present as Golden Guide AI", "Do not iframe HODP"],
    public_demo_suitability: "NOT_UNTIL_SANITIZED",
    evidence_refs: ["GW4_CAPSULE_QADP", "PHASE_Z_EAII_KNOWLEDGE_INTELLIGENCE_ALPHA_A2"],
    publication_recommendation: "NEEDS_SANITIZATION",
    first_exhibit: true,
    notes: "Cite-or-admit local prototype. QADP ≠ Golden Guide AI ≠ Zuno.",
  }),
  rec({
    id: "PROTO-ECOSPHERE-MAP",
    title: "Living Ecosphere Map (read-only)",
    prototype_class: "WORKING",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: ["univ_workstation_navigator"],
    public_safe_identity: "Not Golden Universe Map",
    repo_ref: "dashboard/Html/z-universe-ecosphere-map.html",
    local_data_dependencies: "Hub JSON catalogs (fetch-only)",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Must not be labeled Golden Universe Map", "Catalog contents may be operator-private"],
    public_demo_suitability: "NOT_UNTIL_SANITIZED",
    evidence_refs: ["docs/dashboard/Z_SANCTUARY_LIVING_ECOSPHERE_MAP.md"],
    publication_recommendation: "NEEDS_SANITIZATION",
    first_exhibit: true,
    notes: "A different map surface. Visual connection ≠ the GW-5 six-node Golden Universe Map.",
  }),
  rec({
    id: "PROTO-QA-RP",
    title: "Z-Q&A&RP Pathways & DRP",
    prototype_class: "PARTIAL",
    canonical_record: "grounded_questions_qadp",
    related_records: ["fourteen_drp_protocols"],
    public_safe_identity: "QADP family alias — not a second public Q&A product",
    repo_ref: "dashboard/z-qa-rp/index.html",
    local_data_dependencies: "QA/RP registry JSON",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Collapse to one public QADP story", "No Zuno-as-chatbot"],
    public_demo_suitability: "NOT_UNTIL_SANITIZED",
    evidence_refs: ["docs/Z-QA-RP-ECOSYSTEM-SPEC.md"],
    publication_recommendation: "NEEDS_SANITIZATION",
    first_exhibit: false,
    notes: "Internal alias of grounded questions. Do not exhibit as a separate product.",
  }),
  rec({
    id: "PROTO-HODP-SKK",
    title: "HODP operator dashboard (SKK/RKPK)",
    prototype_class: "PRIVATE",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: ["z_eaii", "univ_workstation_navigator"],
    public_safe_identity: null,
    repo_ref: "dashboard/Html/index-skk-rkpk.html",
    local_data_dependencies: "Many hub JSON reports; Navigator catalog; twin-roots mock",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "high",
    external_network: false,
    sanitization_needs: ["Do not iframe", "localhost references", "operator topology"],
    public_demo_suitability: "NO",
    evidence_refs: ["docs/dashboard/Z_UNIVERSE_WORKSTATION_NAVIGATOR.md"],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "Operator control surface. Contains Navigator but is not the public-safe Navigator page.",
  }),
  rec({
    id: "PROTO-NAV-OPERATOR",
    title: "Universal Workstation Navigator (operator cockpit)",
    prototype_class: "WORKING",
    canonical_record: "univ_workstation_navigator",
    related_records: [],
    public_safe_identity: "Universal Workstation Navigator",
    repo_ref: "dashboard/Html/index-skk-rkpk.html",
    local_data_dependencies: "dashboard/data/z_universe_service_catalog.json",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Use existing shell navigator.html; do not iframe SKK"],
    public_demo_suitability: "USE_SANITIZED_SHELL_ONLY",
    evidence_refs: ["docs/dashboard/Z_UNIVERSE_NAVIGATOR_GREEN_RECEIPT.md"],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "WORKING local UI already has a public-safe page. Operator HTML stays private.",
  }),
  rec({
    id: "PROTO-MORNING-COCKPIT",
    title: "SSWS Morning Cockpit",
    prototype_class: "PRIVATE",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: ["z_eaii"],
    public_safe_identity: null,
    repo_ref: "dashboard/panels/z-ssws-morning-cockpit.html",
    local_data_dependencies: "Operator reports fetch",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "high",
    external_network: false,
    sanitization_needs: ["Ops-centre language", "report internals"],
    public_demo_suitability: "NO",
    evidence_refs: ["docs/PHASE_Z_SSWS_MORNING_COCKPIT_ALPHA_A1.md"],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "Operator morning surface. Not a public operations centre.",
  }),
  rec({
    id: "PROTO-CRYSTAL-DNA",
    title: "Crystal DNA map panel",
    prototype_class: "PARTIAL",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: "Not Golden Universe Map",
    repo_ref: "dashboard/panels/z-crystal-dna-map.html",
    local_data_dependencies: "Drift/report JSON",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Identity vs Golden Universe Map", "private topology"],
    public_demo_suitability: "NO",
    evidence_refs: ["docs/Z_COMPOSED_AWARENESS_PROJECT_WORLD_CRYSTAL_DNA_P0_IMPLEMENTATION_1.md"],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "Another internal map. Do not merge identities.",
  }),
  rec({
    id: "PROTO-AMK-MAP",
    title: "AMK-Goku Main Control Map",
    prototype_class: "PRIVATE",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: null,
    repo_ref: "dashboard/Html/amk-goku-main-control.html",
    local_data_dependencies: "Operator map JSON (readonly companion)",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Steward personal control map", "not public portfolio"],
    public_demo_suitability: "NO",
    evidence_refs: ["docs/PHASE_AMK_MAP_1_GREEN_RECEIPT.md"],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "AMK-MAP-1 is a Steward control map, not Golden Universe Map.",
  }),
  rec({
    id: "PROTO-UCCR-CANVAS",
    title: "Universal Canvas lite",
    prototype_class: "CONCEPT",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: "Not Golden Universe Map",
    repo_ref: "dashboard/panels/z_uccr_universal_canvas_lite.html",
    local_data_dependencies: "Lite/mock panel",
    live_private_api: false,
    sensitive_paths: false,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Must stay visibly concept/lite"],
    public_demo_suitability: "NO",
    evidence_refs: [],
    publication_recommendation: "NEEDS_MORE_EVIDENCE",
    first_exhibit: false,
    notes: "Lite canvas is not the GW-5 map engine and not a 160-node Universe.",
  }),
  rec({
    id: "PROTO-MDGEV",
    title: "Z-MDGEV Eagle Eyes",
    prototype_class: "PRIVATE",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: null,
    repo_ref: "dashboard/z-mdgev/index.html",
    local_data_dependencies: "Dashboard registry; iframe",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["iframe", "operator grid"],
    public_demo_suitability: "NO",
    evidence_refs: [],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "Operator grid with iframe. Do not embed in Golden Website.",
  }),
  rec({
    id: "PROTO-CONSENT-EXPLAINER",
    title: "Consent center / explainer panels",
    prototype_class: "SIMULATED",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: null,
    repo_ref: "dashboard/panels/consent-center.html",
    local_data_dependencies: "Calls /api/consent and /api/audit (not a Golden Website API)",
    live_private_api: true,
    sensitive_paths: true,
    fake_live_telemetry_risk: "high",
    external_network: false,
    sanitization_needs: ["Remove live API POSTs from any public derivative"],
    public_demo_suitability: "NO",
    evidence_refs: [],
    publication_recommendation: "DO_NOT_PUBLISH",
    first_exhibit: false,
    notes: "Looks interactive; talks to hub API routes. Not a public consent product.",
  }),
  rec({
    id: "PROTO-DOCS-PUBLIC",
    title: "docs/public HTML apps (grouped)",
    prototype_class: "PRIVATE",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: null,
    repo_ref: "docs/public/",
    member_count: 4,
    local_data_dependencies: "localhost, Windows path strings, fetch",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Remove local URLs and filesystem strings before any public copy"],
    public_demo_suitability: "NO",
    evidence_refs: [],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "creator_manual, super_chat, z-html-do, snapshot. Scan flagged localhost and Windows paths.",
  }),
  rec({
    id: "PROTO-ZILWA-CLUSTER",
    title: "ZILWA hospitality / life-hub HTML (grouped)",
    prototype_class: "CONCEPT",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: null,
    repo_ref: "dashboard/Html/zilwa-*.html",
    member_count: 26,
    local_data_dependencies: "Mostly static exhibit HTML",
    live_private_api: false,
    sensitive_paths: false,
    fake_live_telemetry_risk: "low",
    external_network: false,
    sanitization_needs: ["Identity, commercial, and children/family surfaces need Steward gates"],
    public_demo_suitability: "NO",
    evidence_refs: [],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "Concept/exhibit cluster. Not first Golden Website exhibits. Some touch children/family themes.",
  }),
  rec({
    id: "PROTO-LEGAL-WORKSTATION",
    title: "Legal lawyer workstation / Lawgrid",
    prototype_class: "PRIVATE",
    canonical_record: null,
    identity_link: "NEEDS_IDENTITY_REVIEW",
    related_records: [],
    public_safe_identity: null,
    repo_ref: "dashboard/Html/z-legal-lawyer-workstation.html",
    local_data_dependencies: "Legal ops reports (readonly companions)",
    live_private_api: false,
    sensitive_paths: true,
    fake_live_telemetry_risk: "medium",
    external_network: false,
    sanitization_needs: ["Legal/personal operator data"],
    public_demo_suitability: "NO",
    evidence_refs: ["docs/PHASE_Z_LEGAL_WORKSTATION_UX_2_GREEN_RECEIPT.md"],
    publication_recommendation: "KEEP_PRIVATE",
    first_exhibit: false,
    notes: "Operator legal surface. Not a public law product.",
  }),
];

function stats(rows, key) {
  const out = {};
  for (const r of rows) {
    const k = r[key];
    out[k] = (out[k] || 0) + 1;
  }
  return out;
}

const visual = {
  schema: "gw6_visual_inventory_v1",
  phase: "GW-6",
  generated_at: "2026-08-27",
  publication: "NONE",
  deployment: "NONE",
  twin_live_records: 0,
  private_browser_exposure: 0,
  note: "Internal inventory. Repo-relative refs are not a public payload. Do not copy these files into the Golden Website shell in this phase.",
  discovery: {
    golden_website_png_count: gwShots.length,
    html_scanned_dashboard_docs_public_shell: 71,
    icis_fixture_svg_count: 3,
  },
  statistics: {
    classified: visualAssets.length,
    first_exhibit: visualAssets.filter((a) => a.first_exhibit).length,
    by_recommendation: stats(visualAssets, "publication_recommendation"),
    by_type: stats(visualAssets, "asset_type"),
  },
  assets: visualAssets,
};

const proto = {
  schema: "gw6_prototype_inventory_v1",
  phase: "GW-6",
  generated_at: "2026-08-27",
  publication: "NONE",
  deployment: "NONE",
  twin_live_records: 0,
  private_browser_exposure: 0,
  note: "Named surfaces plus clusters. 71 HTML files were counted; not each file is a Golden Website exhibit.",
  discovery: {
    html_count_hub_scoped: 71,
    named_or_clustered_records: prototypes.length,
  },
  statistics: {
    classified: prototypes.length,
    first_exhibit: prototypes.filter((a) => a.first_exhibit).length,
    by_class: stats(prototypes, "prototype_class"),
    by_recommendation: stats(prototypes, "publication_recommendation"),
  },
  prototypes,
};

const outVis = path.join(ROOT, "data/golden-website/gw6_visual_inventory.json");
const outProto = path.join(ROOT, "data/golden-website/gw6_prototype_inventory.json");
fs.writeFileSync(outVis, `${JSON.stringify(visual, null, 2)}\n`);
fs.writeFileSync(outProto, `${JSON.stringify(proto, null, 2)}\n`);
if (visual.statistics.first_exhibit !== 6) throw new Error("visual shortlist must be 6");
if (proto.statistics.first_exhibit !== 4) throw new Error("prototype shortlist must be 4");
process.stdout.write(
  JSON.stringify(
    {
      visuals: visual.statistics.classified,
      visual_shortlist: visual.statistics.first_exhibit,
      prototypes: proto.statistics.classified,
      prototype_shortlist: proto.statistics.first_exhibit,
    },
    null,
    2,
  ),
);
